version: "3.8"
services:
  app:
    container_name: docker-mongo-music-app
    restart: always
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/docker-db

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27012:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8083:8081"
    depends_on:
      - mongo
